apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-infra-appset
  namespace: argo-cd
spec:
  generators:
  - list:
      elements:
      - appName: prometheus
        namespace: monitoring
      - appName: vmagent
        namespace: vmetrics
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/Amitk3293/cw-training.git
        targetRevision: HEAD
        path: "applicationsets/infra/{{appName}}"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - values.yaml
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true